<?
$menu["menu300"] = array (
    array("300000", "게시판관리", ""),
    array("300910", "메뉴관리", "$g4[admin_path]/menu_list.php"),
    array("-"),
    array("300100", "게시판관리", "$g4[admin_path]/board_list.php"),
    array("300200", "게시판그룹관리", "$g4[admin_path]/boardgroup_list.php"),
    array("-"),
    array("300510", "게시판스킨목록", "$g4[admin_path]/board_skin.php"),
    array("300520", "게시글 통계", "$g4[admin_path]/stat_write.php"),
    array("300530", "다운로드내역", "$g4[admin_path]/download_list.php"),
    array("-"),
    array("300540", "신고관리", "$g4[admin_path]/singo_list.php"),
    array("300550", "신고해제관리", "$g4[admin_path]/unsingo_list.php"),
    array("300555", "신고사유관리", "$g4[admin_path]/singo_reason_list.php"),
    array("-"),
    array("300560", "휴지통관리", "$g4[admin_path]/recycle_list.php"),
    array("-"),
    array("300300", "배너관리", "$g4[admin_path]/banner_list.php"),
    array("300310", "배너그룹관리", "$g4[admin_path]/banner_group_list.php"),
    array("300320", "배너클릭현황", "$g4[admin_path]/banner_click_list.php"),
    array("-"),
    array("300400", "최근글정렬", "$g4[admin_path]/board_new_sort.php"),
    array("300410", "최근글다시만들기", "$g4[admin_path]/board_new_rebuild.php"),
    array("-"),
    array("300800", "DB Cache", "$g4[admin_path]/dbcache_list.php"),
    array("300810", "이미지관리", "$g4[admin_path]/chimage_list.php"),
    array("300820", "안쓰는이미지관리", "$g4[admin_path]/chimage_unused_list.php"),
    array("300830", "썸네일삭제", "$g4[admin_path]/thumb_clear.php?days=90"),
    array("300840", "임시저장글관리", "$g4[admin_path]/tempsave_list.php"),
);
?>